### ISSUE TITLE
Case insensitivity

### ISSUE THREAD

**Issue by frellan** [AdrianWilczynski/AgGrid.InfiniteRowModel#1]
Hi!

Really neat NuGet-package you got here. I just noticed that all filtering is done on a case-sensitive way though, which is not ideal. It is also not the default client-side AgGrid behavior. Can you just add a `StringComparison.InvariantCultureIgnoreCase` to the contains and equals filtering?

**Comment by AdrianWilczynski** [comment]
Hi. Case insensitivity is a good idea. Sadly EF Core won't translate `StringComparison`. It can be worked around by calling `ToLower`.

I've added an optional `options` parameter with `CaseInsensitive` setting to support this. It's not gonna be enabled by default since it looks like there are performance concerns related to this workaround and SQL Server is case insensitive by default anyway.

I'm planning on pushing this to NuGet soon.

**Comment by frellan** [comment]
Wonderful, very nice of you! So you mean this is partly because I use Postgres? Interesting that SQLServer is different.

**Comment by AdrianWilczynski** [comment]
It should be up on NuGet now.

I'm not well versed in this topic, but it might be worth your time to read up on collations (https://docs.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity) and maybe set case-insensitivity up on database level instead or create some indexes on expressions (https://www.postgresql.org/docs/9.1/indexes-expressional.html) if you're going to use this feature.
___
You can configure case-insensitivity like this:
```csharp
_dbContext.Users.GetInfiniteRowModelBlock(query, new() { CaseInsensitive = true });
```
